INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SURFACEINSPECTOR SurfaceInspector)

FIND_PATH(
    SURFACEINSPECTOR_INCLUDE_DIRS
    NAMES SurfaceInspector/api.h
    HINTS $ENV{SURFACEINSPECTOR_DIR}/include
        ${PC_SURFACEINSPECTOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SURFACEINSPECTOR_LIBRARIES
    NAMES gnuradio-SurfaceInspector
    HINTS $ENV{SURFACEINSPECTOR_DIR}/lib
        ${PC_SURFACEINSPECTOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/SurfaceInspectorTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SURFACEINSPECTOR DEFAULT_MSG SURFACEINSPECTOR_LIBRARIES SURFACEINSPECTOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(SURFACEINSPECTOR_LIBRARIES SURFACEINSPECTOR_INCLUDE_DIRS)
